app = 'crear-videos-subir-youtuve'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  # IMPORTANTE: Desactivamos el autostop automático de Fly
  # para que el código (shutdown_machine) tenga el control total
  auto_stop_machines = false 

[[vm]]
  memory = '1gb'
  cpus = 1
