# fly.toml app configuration file for crear-videos-subir-youtuve

app = 'crear-videos-subir-youtuve'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  # Desactivamos el autostop para que no mate el proceso de renderizado
  auto_stop_machines = false
  auto_start_machines = true
  # Mantenemos una máquina activa para asegurar que termine las tareas de fondo
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  # Subido a 2GB de RAM para evitar el error Out of Memory (OOM)
  memory_mb = 2048
